spring:
  application:
    name: webflux
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9090

scheduler:
  enabled: true
  max-allow-user-count: 1000